### ISSUE TITLE
some errors while trying to access/stream files

### ISSUE THREAD

**Issue by Andy2244** [namjaejeon/cifsd#171]
I get those errors while trying to stream/access movie files via a Win10 mounted share. The streaming seems to work, even with those errors. Those happen every-time the media player opens the file for the first time.

```
kern.err kernel: [155671.337050] kcifsd: smb2_lock:5918: the end offset(ffffffffffffffff) is smaller than the start offset(0)
kern.err kernel: [155671.346691] kcifsd: smb2_lock:6164: failed in taking lock(flags : 1)
kern.err kernel: [155671.393032] kcifsd: smb2_lock:5918: the end offset(ffffffffffffffff) is smaller than the start offset(0)
kern.err kernel: [155671.402664] kcifsd: smb2_lock:6164: failed in taking lock(flags : 1)
kern.err kernel: [155811.193596] kcifsd: smb2_open:2521: failed to find stream name in xattr, rc : -2
kern.err kernel: [155811.906263] kcifsd: buffer_check_err:3405: Buffer Overflow
kern.err kernel: [155811.977204] kcifsd: buffer_check_err:3405: Buffer Overflow
kern.err kernel: [155811.984580] kcifsd: buffer_check_err:3405: Buffer Overflow
kern.err kernel: [155811.992401] kcifsd: buffer_check_err:3405: Buffer Overflow
```

PS: I use the master branch.

**Comment by namjaejeon** [comment]
kern.err kernel: [155811.193596] kcifsd: smb2_open:2521: failed to find stream name in xattr, rc : -2
kern.err kernel: [155811.906263] kcifsd: buffer_check_err:3405: Buffer Overflow
I patched these error message are not showing. these message are not critical error message. and windows used customarily to send them to server. So make them hiding. push them in tree to master branch now.  You can use master again.

kern.err kernel: [155671.337050] kcifsd: smb2_lock:5918: the end offset(ffffffffffffffff) is smaller than the start offset(0)
kern.err kernel: [155671.346691] kcifsd: smb2_lock:6164: failed in taking lock(flags : 1)

That is because between linux and windows lock range are different. Let me think more how do that.
Streaming do probably work fine even though these message is coming.
If you or users of openWRT could feel bad, I will make it invisible once.

**Comment by Andy2244** [comment]
Yeah if they are not really critical or are known issues, better to have them in debug or some other logging option. The log can get really long if you get those all the time, which makes it harder to find the new errors that we should report.

**Comment by namjaejeon** [comment]
Done!
Thanks!

**Comment by namjaejeon** [comment]
I pushed them to master now.

**Comment by Andy2244** [comment]
ok fixed thanks
